models/Product.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\imagine\Image;

/**
 * This is the model class for table "product".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property double $protein
 * @property double $fat
 * @property double $carbohydrate
 * @property double $calorie
 * @property double $dietary_fiber
 * @property double $cholesterol
 * @property double $water
 * @property double $ca
 * @property double $fe
 * @property double $na
 * @property double $k
 * @property double $mg
 * @property double $p
 * @property double $co
 * @property double $cr
 * @property double $cu
 * @property double $mn
 * @property double $s
 * @property double $si
 * @property double $v
 * @property double $zn
 * @property double $mo
 * @property double $f
 * @property double $i
 * @property double $se
 * @property double $b
 * @property double $cl
 * @property double $a
 * @property double $b_car
 * @property double $b1
 * @property double $b2
 * @property double $b4
 * @property double $b5
 * @property double $b6
 * @property double $b7
 * @property double $b9
 * @property double $b12
 * @property double $c
 * @property double $d
 * @property double $e
 * @property double $pp
 * @property double $k_phylloquinone
 * @property double $tryptophan
 * @property double $lysine
 * @property double $methionine
 * @property double $threonine
 * @property double $leucine
 * @property double $isoleucine
 * @property double $phenylalanine
 * @property double $valine
 * @property integer $owner_id
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $copy_from
 * @property integer $category_id
 *
 * @property CategoryOfProduct $category
 * @property Product $copyFrom
 * @property Product[] $products
 * @property User $owner
 *
 * @property \yii\web\UploadedFile $image
 */
class Product extends ActiveRecord {
	public $image;

	public function behaviors() {
		return [
			TimestampBehavior::className(),
		];
	}
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['name', 'required'],
	        ['name', 'string', 'max' => 50],
            ['description', 'string'],
	        ['description', 'filter', 'filter' => function($value) {
		        if(empty($value)) {
			        return null;
		        }
		        return $value;
	        }],
            [['protein', 'fat', 'carbohydrate', 'calorie', 'dietary_fiber', 'cholesterol', 'water', 'ca', 'fe', 'na', 'k', 'mg', 'p', 'co', 'cr', 'cu', 'mn', 's', 'si', 'v', 'zn', 'mo', 'f', 'i', 'se', 'b', 'cl', 'a', 'b_car', 'b1', 'b2', 'b4', 'b5', 'b6', 'b7', 'b9', 'b12', 'c', 'd', 'e', 'pp', 'k_phylloquinone', 'tryptophan', 'lysine', 'methionine', 'threonine', 'leucine', 'isoleucine', 'phenylalanine', 'valine'], 'number'],
	        [
		        'owner_id',
		        'exist',
		        'targetClass' => User::className(),
		        'targetAttribute' => 'id',
		        'when' => function($model) {
			        /* @var $model Product */
			        return $model->owner_id != 0;
		        }
	        ],
	        ['owner_id', 'filter', 'filter' => function($value) {
		        if(empty($value) || $value == 0) {
			        return null;
		        }
		        return $value;
	        }],
	        [
		        'copy_from',
		        'exist',
		        'targetClass' => Product::className(),
		        'targetAttribute' => 'id',
		        'when' => function($model) {
			        /* @var $model Product */
			        return $model->copy_from != 0;
		        }
	        ],
	        ['copy_from', 'filter', 'filter' => function($value) {
		        if(empty($value) || $value == 0) {
			        return null;
		        }
		        return $value;
	        }],
	        [
		        'category_id',
		        'exist',
		        'targetClass' => CategoryOfProduct::className(),
		        'targetAttribute' => 'id',
		        'when' => function($model) {
			        /* @var $model Product */
			        return $model->category_id != 0;
		        }
	        ],
	        ['category_id', 'filter', 'filter' => function($value) {
		        if(empty($value) || $value == 0) {
			        return null;
		        }
		        return $value;
	        }],
	        [
		        'image',
		        'file',
		        'skipOnEmpty' => false,
		        'when' => function($model) {
			        /* @var $model Product */
			        return $model->isNewRecord || !file_exists(\Yii::getAlias('@app/web/i/product') . '/' . $this->id . '.jpg');
		        },
		        'whenClient' => 'function (attribute, value) {
			        return ' . ($this->isNewRecord ? 'true' : 'false') . ' || ' . (!file_exists(\Yii::getAlias('@app/web/i/product') . '/' . $this->id . '.jpg') ? 'true' : 'false') . ';
			    }',
		        'uploadRequired' => 'Необходимо прикрепить картинку.',
	        ],
	        [
		        'image',
		        'file',
		        'extensions' => 'jpg, jpeg, gif',
		        'mimeTypes' => 'image/jpeg, image/gif',
	        ],
        ];
    }

	public function saveImage() {
		if($this->image) {
			if(file_exists(\Yii::getAlias('@app/web/i/product') . '/' . $this->id . '.jpg')) {
				unlink(\Yii::getAlias('@app/web/i/product') . '/' . $this->id . '.jpg');
			}
			if(file_exists(\Yii::getAlias('@app/web/i/product') . '/' . $this->id . '-big.jpg')) {
				unlink(\Yii::getAlias('@app/web/i/product') . '/' . $this->id . '-big.jpg');
			}
			if(file_exists(\Yii::getAlias('@app/web/i/product') . '/' . $this->id . '-small.jpg')) {
				unlink(\Yii::getAlias('@app/web/i/product') . '/' . $this->id . '-small.jpg');
			}

			$this->image->saveAs(\Yii::getAlias('@app/web/i/product') . '/' . $this->id . '.jpg');
			//формируем большую картинку
			Image::thumbnail(
				\Yii::getAlias('@app/web/i/product') . '/' . $this->id . '.jpg',
				640,
				640
			)->save(
				\Yii::getAlias('@app/web/i/product') . '/' . $this->id . '-big.jpg',
				['quality' => 90]
			);
			//формируем маленькую картинку
			Image::thumbnail(
				\Yii::getAlias('@app/web/i/product') . '/' . $this->id . '-big.jpg',
				320,
				320
			)->save(
				\Yii::getAlias('@app/web/i/product') . '/' . $this->id . '-small.jpg',
				['quality' => 70]
			);
		}
	}

	public static function getImageLinks($model, $types = ['source', 'big', 'small']) {
		$ret = [];
		if(file_exists(\Yii::getAlias('@app/web/i/product') . '/' . $model['id'] . '.jpg')) {
			foreach ((array)$types as $type) {
				$ret[$type] = '//' . Yii::$app->request->serverName . '/i/product/' . $model['id'];
				if ($type == 'source') {
					$ret[$type] .= '.jpg';
				} else {
					$ret[$type] .= '-' . $type . '.jpg';
				}
			}
		}
		return $ret;
	}

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'description' => 'Описание',
            'protein' => 'Белки',
            'fat' => 'Жиры',
            'carbohydrate' => 'Углеводы',
            'calorie' => 'Калорийность',
            'dietary_fiber' => 'Пищевые волокна',
            'cholesterol' => 'Холестерин',
            'water' => 'Процент воды',
            'ca' => 'Кальций. Ca, мг',
            'fe' => 'Железо. Fe, мг',
            'na' => 'Натрий. Na, мг',
            'k' => 'Калий. K, мг',
            'mg' => 'Магний. Mg, мг',
            'p' => 'P, мг',
            'co' => 'Co, мг',
            'cr' => 'Cr, мг',
            'cu' => 'Cu, мг',
            'mn' => 'Mn, мг',
            's' => 'S, мг',
            'si' => 'Si, мг',
            'v' => 'V, мг',
            'zn' => 'Zn, мг',
            'mo' => 'Mo, мг',
            'f' => 'F, мг',
            'i' => 'I, мг',
            'se' => 'Se, мг',
            'b' => 'B, мг',
            'cl' => 'Cl, мг',
            'a' => 'A, мг',
            'b_car' => 'B-car, мг',
            'b1' => 'B1, мг',
            'b2' => 'B2, мг',
            'b4' => 'B4, мг',
            'b5' => 'B5, мг',
            'b6' => 'B6, мг',
            'b7' => 'B7, мг',
            'b9' => 'B9, мг',
            'b12' => 'B12, мг',
            'c' => 'C, мг',
            'd' => 'D, мг',
            'e' => 'E, мг',
            'pp' => 'PP, мг',
            'k_phylloquinone' => 'K (филлохинон), мг',
            'tryptophan' => 'Триптофан, мг',
            'lysine' => 'Лизин, мг',
            'methionine' => 'Метионин, мг',
            'threonine' => 'Треонин, мг',
            'leucine' => 'Лейцин, мг',
            'isoleucine' => 'Изолейцин, мг',
            'phenylalanine' => 'Фенилаланин, мг',
            'valine' => 'Валин, мг',
            'owner_id' => 'Владелец',
            'copy_from' => 'Копия от',
            'category_id' => 'Категория',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(CategoryOfProduct::className(), ['id' => 'category_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCopyFrom()
    {
        return $this->hasOne(Product::className(), ['id' => 'copy_from']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProducts()
    {
        return $this->hasMany(Product::className(), ['copy_from' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOwner()
    {
        return $this->hasOne(User::className(), ['id' => 'owner_id']);
    }
}

controllers/ProductController.php
<?php

namespace app\controllers;

use app\extensions\Controller;
use Yii;
use app\models\Product;
use app\models\search\ProductSearch;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ProductController implements the CRUD actions for Product model.
 */
class ProductController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

	/**
	 * Lists all Product models.
	 * @param number|null $category
	 * @return mixed
	 */
    public function actionIndex($category = null) {
	    $query = Product::find()
		    ->where(['NOT', ['description' => null]])
		    ->andWhere(['!=', 'description', '']);

	    if($category) {
		    $query
			    ->andWhere(is_null($category) ? [] : ['category_id' => $category]);
	    }

	    $dataProvider = new ActiveDataProvider([
		    'query' => $query,
		    'pagination' => [
			    'pageSize' => 15,
		    ],
	    ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
	        'category' => $category,
        ]);
    }

	/**
	 * Displays a single Product model.
	 * @param integer $id
	 * @throws NotFoundHttpException
	 * @return mixed
	 */
    public function actionView($id) {
	    $model = Product::find()
		    ->where(['id' => $id])
		    ->andWhere(['owner_id' => null])
		    ->one();
	    if (!$model) {
		    throw new NotFoundHttpException('The requested page does not exist.');
	    }
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Product model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    /*public function actionCreate()
    {
        $model = new Product();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }*/

    /**
     * Updates an existing Product model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    /*public function actionUpdate($id)
    {
        $model = Product::findOne($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }*/

    /**
     * Deletes an existing Product model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    /*public function actionDelete($id)
    {
	    Product::findOne($id)->delete();

        return $this->redirect(['index']);
    }*/

	protected function findModel($id)
	{
		if (($model = Product::findOne($id)) !== null) {
			return $model;
		} else {
			throw new NotFoundHttpException('The requested page does not exist.');
		}
	}
}

views/product/_product.php
<?php
/**
 * Project: Diet (My balanced diet) - Seven Lights
 * User: Evgeny Rusanov
 * E-mail: admin@dudev.ru
 * Site: dudev.ru
 */
use general\ext\Helper;
use yii\helpers\Html;

/* @var $model app\models\Product */
?>
<div class="row row-product">
	<a href="<?= Yii::$app->urlManager->createUrl(['product/view', 'id' => $model['id']]) ?>" class="h2"><?= Html::encode($model['name']) ?></a>
	<? if(isset($model::getImageLinks($model, 'small')['small'])): ?>
		<a href="<?= Yii::$app->urlManager->createUrl(['product/view', 'id' => $model['id']]) ?>" class="small_image_article">
			<img src="<?= $model::getImageLinks($model, 'small')['small'] ?>">
		</a>
	<? endif; ?>
	<?= Helper::cutter($model['description']) ?>
</div>

views/product/index.php
<?php

use app\assets\ProductAsset;
use app\models\CategoryOfProduct;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $category null|int */

if($category && $category = CategoryOfProduct::findOne($category)) {
	/* @var $category CategoryOfProduct */
	$this->title = $category->name;
	$this->params['breadcrumbs'][] = ['label' => 'Продукты', 'url' => ['product/index']];
} else {
	$this->title = 'Продукты';
}
$this->params['breadcrumbs'][] = $this->title;

$this->params['width'] = 900;

ProductAsset::register($this);
?>
<div class="product-index">
	<?=
	ListView::widget([
		'dataProvider' => $dataProvider,
		'itemView' => '_product',
		'layout' => '{items}{pager}',
	])
	?>
</div>

views/product/view.php
<?php

use app\assets\ProductAsset;

/* @var $this yii\web\View */
/* @var $model app\models\Product */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Продукты', 'url' => ['index']];

if($model->category) {
	$this->params['breadcrumbs'][] = [
		'label' => $model->category->name,
		'url' => [
			'product/index',
			'category' => $model->category-> id,
		]
	];
}
$this->params['breadcrumbs'][] = $this->title;

$this->params['width'] = 900;

ProductAsset::register($this);
?>
<div class="row">
	<? if(isset($model::getImageLinks($model, 'small')['small'])): ?>
		<img src="<?= $model::getImageLinks($model, 'small')['small'] ?>" class="product_img">
	<? endif; ?>
	<span><?= $model->description ?></span>
	<h2>Нутриенты на 100 г</h2>
	<div class="nutrients left">
		<table>
			<tr>
				<th>Белки</th>
				<td><span><?= $model->protein ?> г<!--div class="normal">Суточная норма:<br>100 г</div--></span></td>
			</tr>
			<tr>
				<th>Жиры</th>
				<td><span><?= $model->fat ?> г</span></td>
			</tr>
			<tr>
				<th>Углеводы</th>
				<td><span><?= $model->carbohydrate ?> г</span></td>
			</tr>
			<tr>
				<th>Калорийность</th>
				<td><span><?= $model->calorie ?> ккал</span></td>
			</tr>
			<tr>
				<th>Пищевые волокна</th>
				<td><span><?= $model->dietary_fiber ?> г</span></td>
			</tr>
			<tr>
				<th>Холестерин</th>
				<td><span><?= $model->cholesterol ?> г</span></td>
			</tr>
			<tr>
				<th>Вода</th>
				<td><span><?= $model->water ?> %</span></td>
			</tr>
			<tr>
				<th>Кальций (Ca)</th>
				<td><span><?= $model->ca ?> мг</span></td>
			</tr>
			<tr>
				<th>Железо (Fe)</th>
				<td><span><?= $model->fe ?> мг</span></td>
			</tr>
			<tr>
				<th>Натрий (Na)</th>
				<td><span><?= $model->na ?> мг</span></td>
			</tr>
			<tr>
				<th>Калий (K)</th>
				<td><span><?= $model->k ?> мг</span></td>
			</tr>
			<tr>
				<th>Магний (Mg)</th>
				<td><span><?= $model->mg ?> мг</span></td>
			</tr>
			<tr>
				<th>Фосфор (P)</th>
				<td><span><?= $model->p ?> мг</span></td>
			</tr>
			<tr>
				<th>Кобальт (Co)</th>
				<td><span><?= $model->co ?> мг</span></td>
			</tr>
			<tr>
				<th>Хром (Cr)</th>
				<td><span><?= $model->cr ?> мг</span></td>
			</tr>
			<tr>
				<th>Медь (Cu)</th>
				<td><span><?= $model->cu ?> мг</span></td>
			</tr>
			<tr>
				<th>Марганец (Mn)</th>
				<td><span><?= $model->mn ?> мг</span></td>
			</tr>
			<tr>
				<th>Сера (S)</th>
				<td><span><?= $model->s ?> мг</span></td>
			</tr>
			<tr>
				<th>Кремний (Si)</th>
				<td><span><?= $model->si ?> мг</span></td>
			</tr>
			<tr>
				<th>Ванадий (V)</th>
				<td><span><?= $model->v ?> мг</span></td>
			</tr>
			<tr>
				<th>Цинк (Zn)</th>
				<td><span><?= $model->zn ?> мг</span></td>
			</tr>
			<tr>
				<th>Молибден (Mo)</th>
				<td><span><?= $model->mo ?> мг</span></td>
			</tr>
			<tr>
				<th>Фтор (F)</th>
				<td><span><?= $model->f ?> мг</span></td>
			</tr>
			<tr>
				<th>Йод (I)</th>
				<td><span><?= $model->i ?> мг</span></td>
			</tr>
			<tr>
				<th>Селен (Se)</th>
				<td><span><?= $model->se ?> мг</span></td>
			</tr>
		</table>
	</div>
	<div class="nutrients right">
		<table>
			<tr>
				<th>Бор (B)</th>
				<td><span><?= $model->b ?> мг</span></td>
			</tr>
			<tr>
				<th>Хлор (Cl)</th>
				<td><span><?= $model->cl ?> мг</span></td>
			</tr>
			<tr>
				<th>Витамин А</th>
				<td><span><?= $model->a ?> мг</span></td>
			</tr>
			<tr>
				<th>Бета-каротин</th>
				<td><span><?= $model->b_car ?> мг</span></td>
			</tr>
			<tr>
				<th>Витамин B1</th>
				<td><span><?= $model->b1 ?> мг</span></td>
			</tr>
			<tr>
				<th>Витамин B2</th>
				<td><span><?= $model->b2 ?> мг</span></td>
			</tr>
			<tr>
				<th>Витамин B4</th>
				<td><span><?= $model->b4 ?> мг</span></td>
			</tr>
			<tr>
				<th>Витамин B5</th>
				<td><span><?= $model->b5 ?> мг</span></td>
			</tr>
			<tr>
				<th>Витамин B6</th>
				<td><span><?= $model->b6 ?> мг</span></td>
			</tr>
			<tr>
				<th>Витамин B7</th>
				<td><span><?= $model->b7 ?> мг</span></td>
			</tr>
			<tr>
				<th>Витамин B9</th>
				<td><span><?= $model->b9 ?> мг</span></td>
			</tr>
			<tr>
				<th>Витамин B12</th>
				<td><span><?= $model->b12 ?> мг</span></td>
			</tr>
			<tr>
				<th>Витамин C</th>
				<td><span><?= $model->c ?> мг</span></td>
			</tr>
			<tr>
				<th>Витамин D</th>
				<td><span><?= $model->d ?> мг</span></td>
			</tr>
			<tr>
				<th>Витамин E</th>
				<td><span><?= $model->e ?> мг</span></td>
			</tr>
			<tr>
				<th>Витамин PP</th>
				<td><span><?= $model->pp ?> мг</span></td>
			</tr>
			<tr>
				<th title="Витамин K (филлохинон)">Витамин K</th>
				<td><span><?= $model->k_phylloquinone ?> мг</span></td>
			</tr>
			<tr>
				<th>Триптофан</th>
				<td><span><?= $model->tryptophan ?> мг</span></td>
			</tr>
			<tr>
				<th>Лизин</th>
				<td><span><?= $model->lysine ?> мг</span></td>
			</tr>
			<tr>
				<th>Метионин</th>
				<td><span><?= $model->methionine ?> мг</span></td>
			</tr>
			<tr>
				<th>Треонин</th>
				<td><span><?= $model->threonine ?> мг</span></td>
			</tr>
			<tr>
				<th>Лейцин</th>
				<td><span><?= $model->leucine ?> мг</span></td>
			</tr>
			<tr>
				<th>Изолейцин</th>
				<td><span><?= $model->isoleucine ?> мг</span></td>
			</tr>
			<tr>
				<th>Фенилаланин</th>
				<td><span><?= $model->phenylalanine ?> мг</span></td>
			</tr>
			<tr>
				<th>Валин</th>
				<td><span><?= $model->valine ?> мг</span></td>
			</tr>
		</table>
	</div>
	<script type="text/javascript">(function(w,doc) {
			if (!w.__utlWdgt ) {
				w.__utlWdgt = true;
				var d = doc, s = d.createElement('script'), g = 'getElementsByTagName';
				s.type = 'text/javascript'; s.charset='UTF-8'; s.async = true;
				s.src = ('https:' == w.location.protocol ? 'https' : 'http')  + '://w.uptolike.com/widgets/v1/uptolike.js';
				var h=d[g]('body')[0];
				h.appendChild(s);
			}})(window,document);
	</script>
	<div data-share-size="40" data-like-text-enable="false" data-background-alpha="0.0" data-pid="1356620" data-mode="share" data-background-color="#ffffff" data-share-shape="round" data-share-counter-size="12" data-icon-color="#ffffff" data-text-color="#000000" data-buttons-color="#ffffff" data-counter-background-color="#ffffff" data-share-counter-type="disable" data-orientation="horizontal" data-following-enable="false" data-sn-ids="fb.vk.tw.ok.gp." data-selection-enable="true" data-exclude-show-more="false" data-share-style="1" data-counter-background-alpha="1.0" data-top-button="false" class="uptolike-buttons" ></div>
</div>